export const plans = [
  {
    id: "particular",
    name: "Particular",
    price: 1000,
    period: "por publicacion",
    includedVehicles: 1,
    extraVehiclePrice: 1000,
    description: "Ideal para vender tu propio auto con checklist, score y chat interno.",
  },
  {
    id: "reseller",
    name: "Revendedor",
    price: 10000,
    period: "mensual",
    includedVehicles: 3,
    extraVehiclePrice: 1000,
    description: "Perfil publico, catalogo chico, automatizaciones simples y chat.",
  },
  {
    id: "agency",
    name: "Agencia",
    price: 20000,
    period: "mensual",
    includedVehicles: 10,
    extraVehiclePrice: 1000,
    description: "Catalogo completo, perfil profesional, chat y gestion de publicaciones.",
  },
];

export const checklistOptions = {
  motor: ["excelente", "bueno", "regular", "necesita reparacion"],
  caja: ["excelente", "buena", "regular", "falla"],
  trenDelantero: ["sin ruidos", "pequenos ruidos", "necesita revision"],
  amortiguadores: ["excelente", "normales", "para cambiar"],
  cubiertas: ["nuevas", "media vida", "gastadas"],
  frenos: ["excelente", "normales", "necesita service"],
  aire: ["funciona perfecto", "enfria poco", "no funciona"],
  interiores: ["impecables", "buenos", "detalles", "deteriorados"],
  vidrios: ["originales", "reparados", "rajados"],
  pintura: ["original", "repintado parcial", "detalles visibles"],
  choques: ["nunca chocado", "choque leve", "choque estructural"],
};

export const demoVehicles = [
  {
    id: "audi-a4-2021",
    brand: "Audi",
    model: "A4",
    version: "2.0 TFSI S-Tronic",
    year: 2021,
    km: 41000,
    price: 45800000,
    zone: "Palermo, CABA",
    viewLocation: "Av. Santa Fe 3200, CABA",
    availableHours: "Lunes a viernes 9-18 hs, sábados 9-13 hs",
    acceptsTrade: true,
    acceptsFinancing: false,
    seller: "Rivera Select",
    sellerType: "Revendedor",
    score: 8.4,
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    media: [
      { media_type: "photo", storage_path: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80", sort_order: 0 },
      { media_type: "photo", storage_path: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=80", sort_order: 1 },
      { media_type: "photo", storage_path: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1200&q=80", sort_order: 2 },
      { media_type: "photo", storage_path: "https://images.unsplash.com/photo-1441148345475-03a2e82f9719?auto=format&fit=crop&w=1200&q=80", sort_order: 3 },
    ],
    description: "Unidad cuidada, service oficial y excelente presentacion general.",
    checklist: {
      motor: "excelente",
      caja: "excelente",
      trenDelantero: "sin ruidos",
      cubiertas: "media vida",
      frenos: "excelente",
      pintura: "detalles visibles",
    },
  },
  {
    id: "corolla-cross-2022",
    brand: "Toyota",
    model: "Corolla Cross",
    version: "XEI 2.0",
    year: 2022,
    km: 36000,
    price: 39500000,
    zone: "Vicente Lopez",
    viewLocation: "Maipú 450, Vicente López",
    availableHours: "Todos los días de 10-19 hs",
    acceptsTrade: true,
    acceptsFinancing: true,
    seller: "Norte Autos",
    sellerType: "Agencia",
    score: 7.8,
    image: "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1200&q=80",
    media: [
      { media_type: "photo", storage_path: "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1200&q=80", sort_order: 0 },
      { media_type: "photo", storage_path: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80", sort_order: 1 },
      { media_type: "photo", storage_path: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=80", sort_order: 2 },
      { media_type: "photo", storage_path: "https://images.unsplash.com/photo-1546614042-7df3c24c9e5d?auto=format&fit=crop&w=1200&q=80", sort_order: 3 },
    ],
    description: "SUV familiar, service al dia y publicacion con documentacion declarada.",
    checklist: {
      motor: "bueno",
      caja: "buena",
      trenDelantero: "sin ruidos",
      cubiertas: "media vida",
      frenos: "normales",
      pintura: "original",
    },
  },
  {
    id: "honda-cb500f-2019",
    brand: "Honda",
    model: "CB 500F",
    version: "ABS",
    year: 2019,
    km: 22000,
    price: 7800000,
    zone: "Caballito, CABA",
    viewLocation: "Rivadavia 5800, CABA",
    availableHours: "Sábados y domingos 10-17 hs",
    acceptsTrade: false,
    acceptsFinancing: false,
    seller: "Martina Lopez",
    sellerType: "Particular",
    score: 6.9,
    image: "https://images.unsplash.com/photo-1558981285-6f0c94958bb6?auto=format&fit=crop&w=1200&q=80",
    media: [
      { media_type: "photo", storage_path: "https://images.unsplash.com/photo-1558981285-6f0c94958bb6?auto=format&fit=crop&w=1200&q=80", sort_order: 0 },
      { media_type: "photo", storage_path: "https://images.unsplash.com/photo-1449426468159-d96dbf08f19f?auto=format&fit=crop&w=1200&q=80", sort_order: 1 },
      { media_type: "photo", storage_path: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1200&q=80", sort_order: 2 },
      { media_type: "photo", storage_path: "https://images.unsplash.com/photo-1547549082-6bc09f2049ae?auto=format&fit=crop&w=1200&q=80", sort_order: 3 },
    ],
    description: "Moto de uso particular, duerme bajo techo y tiene mantenimiento reciente.",
    checklist: {
      motor: "bueno",
      caja: "buena",
      cubiertas: "media vida",
      frenos: "normales",
      pintura: "detalles visibles",
    },
  },
];

export function formatMoney(value) {
  return new Intl.NumberFormat("es-AR", {
    style: "currency",
    currency: "ARS",
    maximumFractionDigits: 0,
  }).format(value);
}
